//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RezaB.API.MobilExpress.Response {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RezaB.API.MobilExpress.Response.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Error.
        /// </summary>
        internal static string AuthenticationError {
            get {
                return ResourceManager.GetString("AuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Expired.
        /// </summary>
        internal static string CardExpired {
            get {
                return ResourceManager.GetString("CardExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards Found But OTP Required.
        /// </summary>
        internal static string CardFoundOTPRequired {
            get {
                return ResourceManager.GetString("CardFoundOTPRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Card Found.
        /// </summary>
        internal static string CardNotFound {
            get {
                return ResourceManager.GetString("CardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Refused.
        /// </summary>
        internal static string CardRefused {
            get {
                return ResourceManager.GetString("CardRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Not Found.
        /// </summary>
        internal static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV And OTP Required.
        /// </summary>
        internal static string CVVAndOTPRequired {
            get {
                return ResourceManager.GetString("CVVAndOTPRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV Required.
        /// </summary>
        internal static string CVVRequired {
            get {
                return ResourceManager.GetString("CVVRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Card.
        /// </summary>
        internal static string DuplicateCard {
            get {
                return ResourceManager.GetString("DuplicateCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Amount.
        /// </summary>
        internal static string InvalidAmount {
            get {
                return ResourceManager.GetString("InvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Bank POS ID.
        /// </summary>
        internal static string InvalidBankPosId {
            get {
                return ResourceManager.GetString("InvalidBankPosId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Card Number.
        /// </summary>
        internal static string InvalidCardNum {
            get {
                return ResourceManager.GetString("InvalidCardNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Card Token.
        /// </summary>
        internal static string InvalidCardToken {
            get {
                return ResourceManager.GetString("InvalidCardToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Client IP.
        /// </summary>
        internal static string InvalidClientIP {
            get {
                return ResourceManager.GetString("InvalidClientIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Customer ID.
        /// </summary>
        internal static string InvalidCustomerID {
            get {
                return ResourceManager.GetString("InvalidCustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Installment.
        /// </summary>
        internal static string InvalidInstallment {
            get {
                return ResourceManager.GetString("InvalidInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Expiration Month.
        /// </summary>
        internal static string InvalidMonth {
            get {
                return ResourceManager.GetString("InvalidMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OTP.
        /// </summary>
        internal static string InvalidOTP {
            get {
                return ResourceManager.GetString("InvalidOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone No.
        /// </summary>
        internal static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Return URL.
        /// </summary>
        internal static string InvalidReturnURL {
            get {
                return ResourceManager.GetString("InvalidReturnURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Is Not Required.
        /// </summary>
        internal static string InvalidState {
            get {
                return ResourceManager.GetString("InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Transaction ID.
        /// </summary>
        internal static string InvalidTransactionId {
            get {
                return ResourceManager.GetString("InvalidTransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Expiration Year.
        /// </summary>
        internal static string InvalidYear {
            get {
                return ResourceManager.GetString("InvalidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No OTP Sent For Verification.
        /// </summary>
        internal static string NoOTPSentForVerification {
            get {
                return ResourceManager.GetString("NoOTPSentForVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Could Not Be Sent.
        /// </summary>
        internal static string OTPCouldNotSend {
            get {
                return ResourceManager.GetString("OTPCouldNotSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Required.
        /// </summary>
        internal static string OTPRequired {
            get {
                return ResourceManager.GetString("OTPRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Transaction Not Found.
        /// </summary>
        internal static string RefTransactionNotFound {
            get {
                return ResourceManager.GetString("RefTransactionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        internal static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Secure URL Created.
        /// </summary>
        internal static string ThreeDSecureURLCreated {
            get {
                return ResourceManager.GetString("ThreeDSecureURLCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Validation Failed.
        /// </summary>
        internal static string ThreeDValidationFailed {
            get {
                return ResourceManager.GetString("ThreeDValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Late OTP Verification.
        /// </summary>
        internal static string TooLateOTPVerification {
            get {
                return ResourceManager.GetString("TooLateOTPVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Many OTP Verifications Tried.
        /// </summary>
        internal static string TooMuchOTPVerificationTried {
            get {
                return ResourceManager.GetString("TooMuchOTPVerificationTried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Sent Too Quickly.
        /// </summary>
        internal static string TooQuickOTPSent {
            get {
                return ResourceManager.GetString("TooQuickOTPSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined Response Code ({0}).
        /// </summary>
        internal static string UndefinedResponseCode {
            get {
                return ResourceManager.GetString("UndefinedResponseCode", resourceCulture);
            }
        }
    }
}
